[package]
name = "algo"
version = "0.1.0"
authors = ["Eugene Kalinin <e.v.kalinin@gmail.com>"]

[features]
unstable = []

[dependencies]

[lib]
name = "algo"
path = "src/lib.rs"

[[bin]]
name = "algotest"
path = "src/main.rs"